---
title: "interactivity_practice"
author: "Yangwei Yan / Yunqiu Yao"
date: "11/14/2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

# Problem 1

Create a flexdashboard using plotly for interactive graphics using `Instacart` dataset.

```{r}
## Import and clean the data "Instacart".
instacart = read_csv("./instacart_train_data.csv.zip") %>%
  clean_names()
```



Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot

What is the distribution of the order hour of the day for each department?

```{r}
instacart %>%
  mutate(department = fct_reorder(department, order_hour_of_day, IQR)) %>%
  select(department, order_hour_of_day) %>%
## The IQR of each department was in increasing order.
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Barplot

How many items ordered for each department? 
```{r}

```

### Product reorder ratio

Products with a high number of orders are naturally more likely to be reordered. However, there seems to be a ceiling effect.

```{r }

```





