---
title: "Flexdashboard for Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r}
## Import and clean the data "Instacart".
instacart = read_csv("./instacart_train_data.csv.zip") %>%
  clean_names()
```


Column {data-width=500}
-----------------------------------------------------------------------

### Barplot - Item counts by aisles

How many items ordered for each department?

```{r}
instacart %>% 
  count(department) %>% 
  rename(items = n) %>% 
  mutate(department = fct_reorder(department,items)) %>% 
  plot_ly(x = ~department, y = ~items, color = ~department, type = "bar")
```



Column {data-width=500}
-----------------------------------------------------------------------

### Boxplot - Order hour of the day

What is the distribution of the order hour of the day for each department? It seems that most orders are between 8.00-18.00.

```{r}
instacart %>%
  mutate(department = fct_reorder(department, order_hour_of_day, IQR)) %>%
  select(department, order_hour_of_day) %>%
## The IQR of each department was in increasing order.
  plot_ly(y = ~order_hour_of_day, color = ~department, type = "box", colors = "Set2")
```



### Scatterplot - Product reorder ratio 

Products with a high number of orders are naturally more likely to be reordered. However, there seems to be a ceiling effect.

```{r }
## reorder
reordered = instacart %>% 
  filter(reordered == 1) %>% 
  count(product_id) %>% 
  rename(reordered = n)

instacart %>% 
  count(product_id, department) %>%
  rename(ordered = n) %>% 
  left_join(reordered) %>% 
  mutate(reordered = ifelse(is.na(reordered),0,reordered),
         reo_ratio = reordered/ordered,
         tlabel = str_c("Product_ID: ", product_id, product_id, '\nDepartment: ', department)) %>%
  plot_ly(x = ~ordered,y = ~reo_ratio, type = "scatter", mode = "markers", alpha = 0.5, text = ~tlabel, color = I("black"))
```



